"$schema" = "node_modules/wrangler/config-schema.json"
name = "jagrit-gumber-portfolio"
compatibility_date = "2025-06-27"

[assets]
not_found_handling ="single-page-application"

[observability]
enabled = true
